# Generated by Django 4.1 on 2022-09-01 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('params', models.TextField()),
                ('image', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='SubItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('params', models.TextField()),
                ('image', models.CharField(max_length=256)),
                ('item', models.ManyToManyField(to='Api.item')),
            ],
        ),
    ]
