# Generated by Django 4.1 on 2022-09-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='image',
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.TextField(default='some text'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='SubItem',
        ),
    ]
