# Generated by Django 4.1 on 2022-09-01 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Api', '0002_remove_item_image_item_images_delete_subitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='images',
        ),
    ]
